//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;
using System.Collections.Generic;


		public class MonthCalendar{
	
		private  List<List<Box>> Dates;
		private  int numberOfMonth;
		private  int numberOfDays;
		private  string nameOfMonth;

	public MonthCalendar(double xPosition, double yPosition, double width, double height){
		setDates (xPosition, yPosition, width, height);
		string datePatt = @"MM";
		DateTime saveNow = DateTime.Now;
		string dtString = saveNow.ToString(datePatt);
		this.numberOfMonth = Int32.Parse (dtString[1].ToString());
		setNumberOfDays();
	}

	void setDates(double xPosition, double yPosition, double width, double height){
			this.Dates = new List<List<Box>>();
			double boxXPosition = xPosition;
			double boxYPosition = yPosition;
			for (int y = 0; y < 5; y++) {
				Dates.Add(new List<Box>());
				for(int x = 0; x < 7; x++){
					boxXPosition += width/7;
					Dates[y].Add(new Box(boxXPosition, boxYPosition, width/7, height/5, Color.red));
				}
				boxYPosition += height/5;
				boxXPosition = xPosition;
			}
		}

	public List<List<Box>> getDates(){
		return this.Dates;
	}

	private void setNumberOfDays(){
		for (int counter = 1; counter < 13; counter++) {
			if(this.numberOfMonth < 8 ){
				if(this.numberOfMonth % 2 != 0){
					this.numberOfDays = 31;
				}else{
					this.numberOfDays = 30;
				}
			}else if(this.numberOfMonth > 7){
				if(this.numberOfMonth % 2 == 0){
					this.numberOfDays = 31;
				}else{
					this.numberOfDays = 30;
				}
			}

			string datePatt = @"yyyy";
			DateTime saveNow = DateTime.Now;
			string dtString = saveNow.ToString(datePatt);
			if(this.numberOfMonth == 2){
				this.numberOfDays = 28;
				if(Int32.Parse(dtString) % 4 == 0){
					this.numberOfDays = 29;
				}
			}
		}
	}

	public int getNumberOfDays(){
		return this.numberOfDays;
	}

	void setNameOfMonth(){
		switch (this.numberOfMonth) {
			case 1: this.nameOfMonth = "january";
				break;
			case 2: this.nameOfMonth = "February";
				break;
			case 3: this.nameOfMonth = "March";
				break;
			case 4: this.nameOfMonth = "April";
				break;
			case 5: this.nameOfMonth = "May";
				break;
			case 6: this.nameOfMonth = "June";
				break;
			case 7: this.nameOfMonth = "July";
				break;
			case 8: this.nameOfMonth = "August";
				break;
			case 9: this.nameOfMonth = "September";
				break;
			case 10: this.nameOfMonth = "October";
				break;
			case 11: this.nameOfMonth = "November";
				break;
			case 12: this.nameOfMonth = "December";
				break;
		}
	}

	public string getNameOfMonth(){
		return this.nameOfMonth;
	}


}




